name: Build and Push Docker Image

on:
  push:
    branches:
      - develop
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/my-image:${{ github.sha }}

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "Deploying to staging environment..."
          # Replace with actual deployment command to staging

      - name: Deploy to Production
        if: github.ref_type == 'tag'
        run: |
          echo "Deploying to production environment..."
          # Replace with actual deployment command to production

      - name: Update Kubernetes Deployment
        if: github.ref_type == 'tag'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.K8S_HOST }}
          username: ${{ secrets.K8S_USERNAME }}
          password: ${{ secrets.K8S_PASSWORD }}
          script: |
            echo "Updating Kubernetes deployment..."
            # Replace with actual Kubernetes deployment update command

      - name: Notify Slack
        if: always()
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          text: 'Build ${{ job.status }} for branch ${{ github.ref }} with image tag ${{ github.sha }}'
          author_name: GitHub Actions
          author_icon: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          color: ${{ job.status == 'success' && '#2cbe4e' || '#cb2431' }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
